export enum ProfileUpdateFailureCause {
    INVALID_EMAIL = 'INVALID_EMAIL',
    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
    WEAK_PASSWORD = 'WEAK_PASSWORD',
    INVALID_NAME = 'INVALID_NAME',
    INVALID_SETTINGS = 'INVALID_SETTINGS',
    OTHER = 'OTHER'
}